/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphql4smr.demo;

import graphql4smr.lib.GraphQL4SMR;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        String query = "{counter}";


        GraphQL4SMR graphql4smr = new GraphQL4SMR();
        String response = graphql4smr.request(query);
        System.out.println(response);

        assertEquals("{\"data\":{\"counter\":0}}",response);
    }
}
